### ISSUE TITLE
Some info

### ISSUE THREAD

**Issue by erezger** [eladcn/nuance-nodejs#1]
Hello i am trying using this package

what is the loadFile? what file should load? cant be replaced by string text? like "Hello World".
what is the response back? its array buffer? text? should be convert to a wav file?

sorry for the question Thanks for the help

**Comment by eladcn** [comment]
Hey,
The purpose of this package is to convert an audio file that contains speech into text by sending the file to a service called Nuance.

The loadFile method requires a path to the audio file you would like to send to Nuance.
The response of loadFile tells you if the file was loaded or not (if the package could fetch the file's data or not).
After you use the loadFile function, you should use the sendRequest method which then sends the request to Nuance, then you receive the analyzed text back from the method.

Please read the README.md file which includes a sample code of using this package.

**Comment by eladcn** [comment]
Added text-to-speech support.
Issue closed.
